sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run report-coverage
branches:
  only:
    - master
